name: kantor_lurah
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.160+161
environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  web_socket_channel: ^3.0.3
  shared_preferences: ^2.5.4
  image_picker: ^1.2.1
  firebase_core: ^4.4.0
  print_bluetooth_thermal: ^1.1.9
  firebase_crashlytics: ^5.0.6
  permission_handler: ^12.0.1
  flutter_esc_pos_utils: ^1.0.1
  image: ^4.2.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
  cached_network_image: ^3.4.1
  crypto: ^3.0.7
  syncfusion_flutter_charts: ^30.1.40
  mobile_scanner: ^7.0.1
  device_info_plus: ^12.3.0
  share_plus: ^12.0.1
  excel: ^4.0.6
  path_provider: ^2.1.5
  webview_flutter: ^4.13.1
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  google_sign_in: ^6.2.2
  screenshot: ^3.0.0
  image_gallery_saver_plus: ^4.0.1
  safe_device: ^1.3.8
  printing: ^5.13.4
  pdf: ^3.11.1
  audioplayers: ^6.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/
    - assets/menu_icon/
    - assets/image/
    - assets/audio/
flutter_launcher_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"